apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    usage: "mongodb"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfsshare
    server: 10.240.0.5
