apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb-rs.fullname" . }}
  labels:
    app: {{ template "mongodb-rs.name" . }}
    chart: {{ template "mongodb-rs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mongo
  selector:
    app: {{ template "mongodb-rs.name" . }}
    release: {{ .Release.Name }}
